kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: arm64
steps:
- name: build-docker
  environment:
    PASSWORD:
      from_secret: docker_pass
  commands:
  - echo "Test drone runner"
