name: profile_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_sticky_widgets: ^0.0.3
  google_fonts: ^4.0.4
  camera: ^0.10.5+2
  image_picker: ^0.8.7+5
  image_cropper: ^4.0.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

